### ISSUE TITLE
use the latest Popolo schema with richer other_names

### ISSUE THREAD

**Issue by mhl** [mysociety/popit-api#47]
@jpmckinney has updated the Popolo spec so that names in `other_names` have the same elements as a name at the top level: https://github.com/opennorth/popolo-spec/commit/1440ce26b2d768c290eff13bc24e76fb3559456e

(It'd be worth checking that we're not out-of-date in other respects at the same time.)

**Comment by chrismytton** [comment]
Fixed in https://github.com/mysociety/popit-api/commit/2c9b67ef93bed7734a1cd5289690db0d432b0612
