### ISSUE TITLE
Bulk loading?

### ISSUE THREAD

**Issue by martinszy** [mysociety/popit-api#58]
Hi, I intend to create my own instance of pop-it and I want to load all the data locally, is is possible to use a method via API or otherwise to load the whole database in one swoop instead of making thousands of calls to the API?

Thanks.

**Comment by chrismytton** [comment]
The API now has an importer as of https://github.com/mysociety/popit-api/pull/126, hooray! Still needs to be documented though, which is being tracked by https://github.com/mysociety/popit.poplus.org/issues/45.
